version: 2
sources:
  - name: raw # Alias du dataset
    schema: gz_raw_data # chemin du dataset ->schema is the name of the dataset in BigQuery
    tables:
      - name: sales # Alias de la table
        identifier: raw_gz_sales # nom de la table dans BigQuery
        description: sales of Greenweez / we have on row per product_id found in each orders_id
        columns:
           - name: date_date
             description: date of purchase
           - name: orders_id
             description: type integer
             tests:
              - not_null
              - unique
           - name: pdt_id
             description: id du produit vendu
           - name: revenue
             description:  turnover for 1 unit of pdt_id
           - name: quantity
             description:  quantité vendue
      - name: product
        identifier: raw_gz_product
      - name: ship
        identifier: raw_gz_ship

        #You can now access your sources
        #with {{source(’raw’, ‘sales’)}} instead of{{source(’gz_raw_data’, ‘raw_gz_sales’)}}.
